apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap-env
spec:
  containers:
  - name: app-container
    image: nginx
    env:
    - name: CONFIG_KEY1
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: config-key1